project_id = "vbffikdzwqovwttfdhex"

[functions.gd-conductor]
verify_jwt = false

[functions.gd-topics]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.drill-feedback]
verify_jwt = false

[functions.transcription-correction]
verify_jwt = false